### ISSUE TITLE
Is this repo mantained?

### ISSUE THREAD

**Issue by lubbo** [pksprojects/ElasticSwift#11]

**Comment by prafsoni** [comment]
Yes, it is. I update and fix issues as requested and/or needed. The current roadmap is to get `ElasticSwift` to beta by the end of June which will include `es-6.8.x` API and Swift 5. Since there are more people use 5.x than 7.x next quarter will focus on releasing stable versions compatible with es 5.x and 6.x. 7.x will be next in the queue. Release timelines will be much clear after the release of beta next month.

**Comment by lubbo** [comment]
I’m working with ES 7.x.
I’m fixing some basic features and tests as well.
Take a look on my fork, I’d be glad to contribute if possible.

**Comment by prafsoni** [comment]
Awesome contributions are welcome. I would recommend you to look at `query-builders` branch as I am in the process of making ElasticSwift API familiar to Java Elasticsearch Rest Client

**Comment by lubbo** [comment]
I’ve actually made a branch from it
